=== andreiyusupau/java-web-development/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="Candy" abstract="true">
			<xsd:sequence>
				<xsd:element name="Name" type="xsd:string"/>
				<xsd:element name="Energy" type="xsd:int"/>
				<xsd:element name="Value" type="Value"/>
				<xsd:element name="Production">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:string">
								<xsd:attribute name="country" type="xsd:string" use="required"/>
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		<xsd:attribute name="id" type="xsd:ID" use="required" />
	</xsd:complexType>

	<xsd:complexType name="Chocolate">
		<xsd:complexContent>
			<xsd:extension base="Candy">
				<xsd:sequence>
					<xsd:element name="Ingredients" type="Chocolate-ingredients"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Hard-candy">
		<xsd:complexContent>
			<xsd:extension base="Candy">
				<xsd:sequence>
					<xsd:element name="Ingredients" type="Hard-candy-ingredients"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Liquorice">
		<xsd:complexContent>
			<xsd:extension base="Candy">
				<xsd:sequence>
					<xsd:element name="Ingredients" type="Liquorice-ingredients"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Marshmallow">
		<xsd:complexContent>
			<xsd:extension base="Candy">
				<xsd:sequence>
					<xsd:element name="Ingredients" type="Marshmallow-ingredients"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Toffee">
		<xsd:complexContent>
			<xsd:extension base="Candy">
				<xsd:sequence>
					<xsd:element name="Ingredients" type="Toffee-ingredients"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Ingredients" abstract="true">
		<xsd:sequence>
			<xsd:element name="Water">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:int">
							<xsd:attribute name="prepared" type="xsd:boolean" default="false"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="Sugar">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:int">
							<xsd:attribute name="type" type="xsd:string" default="white"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Chocolate-ingredients">
		<xsd:complexContent>
			<xsd:extension base="Ingredients">
				<xsd:sequence>
					<xsd:element name="Chocolate">
						<xsd:complexType>
							<xsd:simpleContent>
								<xsd:extension base="xsd:int">
									<xsd:attribute name="type" type="xsd:string" use="required"/>
								</xsd:extension>
							</xsd:simpleContent>
						</xsd:complexType>
					</xsd:element>
					<xsd:element name="Nuts">
						<xsd:complexType>
							<xsd:simpleContent>
								<xsd:extension base="xsd:int">
									<xsd:attribute name="type" type="xsd:string" use="required"/>
								</xsd:extension>
							</xsd:simpleContent>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Hard-candy-ingredients">
		<xsd:complexContent>
			<xsd:extension base="Ingredients">
				<xsd:sequence>
					<xsd:element name="Citric-acid" type="xsd:int"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Liquorice-ingredients">
		<xsd:complexContent>
			<xsd:extension base="Ingredients">
				<xsd:sequence>
					<xsd:element name="Liquorice-extract" type="xsd:int"/>
					<xsd:element name="Starch" type="xsd:int"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Marshmallow-ingredients">
		<xsd:complexContent>
			<xsd:extension base="Ingredients">
				<xsd:sequence>
					<xsd:element name="Gelatin" type="xsd:int"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Toffee-ingredients">
		<xsd:complexContent>
			<xsd:extension base="Ingredients">
				<xsd:sequence>
					<xsd:element name="Butter" type="xsd:int"/>
					<xsd:element name="Flour" type="xsd:int"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>


	<xsd:complexType name="Value">
		<xsd:sequence>
			<xsd:element name="Proteins" type="xsd:decimal"/>
			<xsd:element name="Fats" type="xsd:decimal"/>
			<xsd:element name="Carbohydrates" type="xsd:decimal"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="Candies">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element name="Liquorice" type="Liquorice" />
				<xsd:element name="Toffee" type="Toffee" />
				<xsd:element name="Marshmallow" type="Marshmallow" />
				<xsd:element name="Chocolate" type="Chocolate" />
				<xsd:element name="Hard-candy" type="Hard-candy" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== andreiyusupau/java-web-development/candies.xml
<?xml version="1.1" encoding="UTF-8"?>
<Candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation = "schema.xsd">
    <Chocolate id="ID-1">
        <Name>"Alpen Gold"</Name>
        <Energy>250</Energy>
        <Value>
            <Proteins>4</Proteins>
            <Fats>5</Fats>
            <Carbohydrates>14</Carbohydrates>
        </Value>
        <Production country="Ukraine">"Roshen"</Production>
        <Ingredients>
            <Water>2</Water>
            <Sugar>170</Sugar>
            <Chocolate type="dark">100</Chocolate>
            <Nuts type="forest">123</Nuts>
        </Ingredients>
    </Chocolate>

    <Hard-candy id="ID-2">
        <Name>"Jelly"</Name>
        <Energy>200</Energy>
        <Value>
            <Proteins>2</Proteins>
            <Fats>3</Fats>
            <Carbohydrates>4</Carbohydrates>
        </Value>
        <Production country="Belarus">"Spartacus"</Production>
        <Ingredients>
            <Water>2</Water>
            <Sugar>100</Sugar>
            <Citric-acid>100</Citric-acid>
        </Ingredients>
    </Hard-candy>

    <Liquorice id="ID-3">
        <Name>"SomeLiquorice"</Name>
        <Energy>150</Energy>
        <Value>
            <Proteins>4</Proteins>
            <Fats>3</Fats>
            <Carbohydrates>4</Carbohydrates>
        </Value>
        <Production country="Belarus">Red Foodish</Production>
        <Ingredients>
            <Water>2</Water>
            <Sugar type="brown">120</Sugar>
            <Liquorice-extract>90</Liquorice-extract>
            <Starch>110</Starch>
        </Ingredients>
    </Liquorice>

    <Toffee id="ID-4">
        <Name>"Toffy"</Name>
        <Energy>50</Energy>
        <Value>
            <Proteins>4</Proteins>
            <Fats>5</Fats>
            <Carbohydrates>15</Carbohydrates>
        </Value>
        <Production country="Ukraine">Roshen</Production>
        <Ingredients>
            <Water>2</Water>
            <Sugar type="cane">70</Sugar>
            <Butter>3</Butter>
            <Flour>53</Flour>
        </Ingredients>
    </Toffee>

    <Marshmallow id="ID-5">
        <Name>"Marshmallow"</Name>
        <Energy>50</Energy>
        <Value>
            <Proteins>4</Proteins>
            <Fats>5</Fats>
            <Carbohydrates>15</Carbohydrates>
        </Value>
        <Production country="Ukraine">Roshen</Production>
        <Ingredients>
            <Water>2</Water>
            <Sugar type="brown">70</Sugar>
            <Gelatin>3</Gelatin>
        </Ingredients>
    </Marshmallow>

</Candies>
